package task5.util;

import task5.exception.ValidationException;

/**
 * @author Oleh Fliurkevych
 */
public class ExceptionUtils {
  
  

}
